setup/urls.py
from django.contrib import admin
from django.urls import path
from todos.views import (
    todo_home,
    todo_repetir,
    todo_update,
    FichaView,
    receber_dados,
    atualizar_dados,
    ficha_toggle_pendente,
    ficha_toggle_active,
    produto_toggle_active,
    plantio_toggle_active,
    upload_excel_file,
    ImprimirFicha,
    muda_cod,
    sync_db_view,
    down_db_view,
    FichaFiltro,
    FichaListView,
    PlantioListView,
    PlantioCreateView,
    PlantioUpdateView,
    PlantioDeleteView,
    AtividadePListView,
    AtividadePCreateView,
    AtividadePUpdateView,
    AtividadePDeleteView,
    ProdutosCreateView,
    ProdutosListView,
    ProdutosUpdateView,
    ProdutosDeleteView,
    TipoAplicacaoListView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", todo_home, name="home_page"),
    path("ficha/toggle/<int:pk>", ficha_toggle_active, name="ficha_toggle_active"),
    path(
        "ficha/toggle_p/<int:pk>", ficha_toggle_pendente, name="ficha_toggle_pendente"
    ),
    path("upload_excel/", upload_excel_file, name="upload_excel"),
    path("sync/", sync_db_view, name="sync_db_view"),
    path("down/", down_db_view, name="down_db_view"),
    path("sync/", muda_cod, name="muda_cod"),
    path("ficha/view/<int:pk>/", FichaView, name="ficha_view"),
    path("ficha/imprimir/<int:pk>/", ImprimirFicha, name="imprimir_ficha"),
    path("update/<int:pk>", todo_update, name="ficha_update"),
    path("repetir/<int:pk>", todo_repetir, name="ficha_repetir"),
    path("receber_dados/", receber_dados, name="receber_dados"),
    path("atualizar_dados/", atualizar_dados, name="atualizar_dados"),
    path("ficha/", FichaListView.as_view(), name="ficha_list"),
    path("ficha/relatorio/", FichaListView.as_view(), name="ficha_relatorio"),
    path("ficha_filtro/", FichaFiltro.as_view(), name="ficha_filtro"),
    path(
        "ficha_filtro/relatorio/", FichaFiltro.as_view(), name="ficha_filtro_relatorio"
    ),
    path("plantio", PlantioListView.as_view(), name="plantio_list"),
    path("plantio/create/", PlantioCreateView.as_view(), name="plantio_create"),
    path("plantio/update/<int:pk>", PlantioUpdateView.as_view(), name="plantio_update"),
    path("plantio/toggle/<int:pk>", plantio_toggle_active, name="plantio_toggle_active"),
    path("plantio/delete/<int:pk>", PlantioDeleteView.as_view(), name="plantio_delete"),
    path("atividade", AtividadePListView.as_view(), name="atividade_list"),
    path("atividade/create/", AtividadePCreateView.as_view(), name="atividade_create"),
    path(
        "atividade/update/<int:pk>",
        AtividadePUpdateView.as_view(),
        name="atividade_update",
    ),
    path(
        "atividade/delete/<int:pk>",
        AtividadePDeleteView.as_view(),
        name="atividade_delete",
    ),
    path("produto", ProdutosListView.as_view(), name="produtos_list"),
    path("produto/create/", ProdutosCreateView.as_view(), name="produtos_create"),
    path(
        "produtos/update/<int:pk>",
        ProdutosUpdateView.as_view(),
        name="produtos_update",
    ),
    path(
        "produto/toggle/<int:pk>", produto_toggle_active, name="produto_toggle_active"
    ),
    path(
        "produtos/delete/<int:pk>", ProdutosDeleteView.as_view(), name="produtos_delete"
    ),
    path("aplicacoes", TipoAplicacaoListView.as_view(), name="aplicacao_list"),
]

todos/models.py
from django.db import models
    
class Produtos(models.Model):
    data_criada = models.DateTimeField(
        verbose_name="Data de criação", blank=False, auto_now_add=False
    )
    data_atualizado = models.DateTimeField(
        verbose_name="Data da aplicação",
        auto_now=True,
        auto_now_add=False,
    )
    produto = models.CharField(
        verbose_name="Produto", max_length=50, null=False, blank=False
    )
    codigo = models.IntegerField(verbose_name="Codigo", null=False)
    descricao = models.CharField(
        verbose_name="Descrição", max_length=50, null=False, blank=False
    )
    ativo = models.BooleanField(default=True)


class Plantio(models.Model):
    data_criada = models.DateTimeField(
        verbose_name="Data de criação", blank=False, auto_now_add=False
    )
    data_atualizado = models.DateTimeField(
        verbose_name="Data da aplicação",
        auto_now=True,
        auto_now_add=False,
    )
    nome_pl = models.CharField(
        verbose_name="Plantio", max_length=50, null=False, blank=False
    )
    cultura = models.CharField(
        verbose_name="Cultura", max_length=50, null=False, blank=False
    )
    pivo = models.CharField(
        verbose_name="Pivo", max_length=10, null=False, blank=False
    )
    area = models.DecimalField(verbose_name="Área", decimal_places=4, max_digits=8)
    fazenda = models.CharField(
        verbose_name="fazenda", max_length=50, null=False, blank=False
    )
    ativo = models.BooleanField(default=True)


class AtividadeP(models.Model):
    data_criada = models.DateTimeField(
        verbose_name="Data de criação", blank=False, auto_now_add=False
    )
    data_atualizado = models.DateTimeField(
        verbose_name="Data da aplicação",
        auto_now=True,
        auto_now_add=False,
    )
    nome = models.CharField(
        verbose_name="Atividade", max_length=10, null=False, blank=False
    )
    # descicao = models.CharField(
    #    verbose_name="Descrição", max_length=100, null=False, blank=False
    # )
    ativo = models.BooleanField(default=True)



class TipoAplicacao(models.Model):
    nome_tipo = models.CharField(
        verbose_name="Irrigador", max_length=50, null=False, blank=False
    )
    ativo = models.BooleanField(default=True)


class FichaCampo(models.Model):
    data_criada = models.DateTimeField(
        verbose_name="Data de criação", blank=False, auto_now_add=False
    )
    data_atualizado = models.DateTimeField(
        verbose_name="Data de modificação",
        null=True,
        auto_now=True,
        auto_now_add=False,
    )
    data_aplicada = models.DateField(
        verbose_name="Data aplicação", blank=False, auto_now=False, auto_now_add=False
    )
    volume = models.IntegerField(verbose_name="Volume", null=False)
    totalarea = models.FloatField(verbose_name="totalArea", null=True)
    totalareaap = models.FloatField(verbose_name="totalAreaAp", null=True)
    totalcalda = models.FloatField(verbose_name="totalCalda", null=True)
    tqn1 = models.FloatField(verbose_name="tqn1", null=True)
    tqn2 = models.FloatField(verbose_name="tqn2", null=True)
    tqn3 = models.FloatField(verbose_name="tqn3", null=True)
    capacidade = models.IntegerField(verbose_name="Capacidade", null=False)
    plantio = models.JSONField()
    atividade = models.ForeignKey(AtividadeP, on_delete=models.CASCADE)
    tipo_aplicacao = models.ForeignKey(TipoAplicacao, on_delete=models.CASCADE)
    dados = models.JSONField()
    obs = models.TextField(null=True, blank=True)
    pendente = models.BooleanField(default=False)
    ativo = models.BooleanField(default=True)

todos/forms.py
from django import forms
from .models import Produtos


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produtos
        fields = ["produto", "codigo", "descricao"]
        widgets = {
            "produto": forms.Select(
                attrs={
                    "class": "select2",
                    "data-placeholder": "Selecione um produto...",
                }
            ),
        }


class area_form(forms.Form):
    area = forms.FloatField(label="Área", required=False)

todos/views.py
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    View,
    DetailView,
)
import pandas as pd
from django.db.models.functions import Cast
from django.db.models import CharField, Value
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseRedirect
from django.db.models import Max
import pytz
from datetime import datetime
from django.utils import timezone
import json
from todos.routers import (
    DatabaseSynchronizer,
    DatabaseDownloader,
    ModificarProdutoRouter,
)

from .models import AtividadeP, Produtos, TipoAplicacao, Plantio, FichaCampo

from django.shortcuts import render

def muda_cod(request):
    response = ModificarProdutoRouter.modificar_produtos()

    return response

def sync_db_view(request):
    DatabaseSynchronizer.sync_db_atividade()
    DatabaseSynchronizer.sync_db_plantio()
    DatabaseSynchronizer.sync_db_produto()
    DatabaseSynchronizer.sync_db()
    return HttpResponseRedirect(reverse("ficha_list"))


def down_db_view(request):
    DatabaseDownloader.sync_db_atividadeb()
    return HttpResponseRedirect(reverse("ficha_list"))

class FichaFiltro(ListView):
    model = FichaCampo
    template_name = "fichadeaplicacao_list.html"
    context_object_name = "fichacampo_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["plantios"] = Plantio.objects.all()
        context["atividades"] = AtividadeP.objects.all()
        context["tipo_irrigadores"] = TipoAplicacao.objects.all()

        for ficha in context["fichacampo_list"]:
            for item in ficha.dados:
                if "produto" in item:
                    cod_produto = item["produto"]
                    produto = Produtos.objects.get(codigo=cod_produto)
                    item["nome_produto"] = produto.produto
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        
        atividade_filter = self.request.GET.get("atividade_filter")
        plantio_filter = self.request.GET.get("plantio_filter")
        status_filter = self.request.GET.get("status_filter")
        start_date = self.request.GET.get("start_date")
        end_date = self.request.GET.get("end_date")

        if start_date and end_date:
            print(start_date, end_date)
            queryset = queryset.filter(data_criada__range=(start_date, end_date))
        else:
            if start_date:
                queryset = queryset.filter(data_criada__date=start_date)

        if atividade_filter:
            queryset = queryset.filter(atividade__id=atividade_filter)

        if plantio_filter:
            queryset = queryset.annotate(
                plantio_text=Cast('plantio', output_field=CharField())
            )
            
            queryset = queryset.filter(plantio_text__contains=plantio_filter)

        if status_filter is not None:
            if status_filter == "true":
                queryset = queryset.filter(pendente=False)
            elif status_filter == "false":
                queryset = queryset.filter(pendente=True)

        return queryset.order_by("data_aplicada")

    def get_template_names(self):
        if "relatorio" in self.request.path:
            return ["fichadeaplicacao_relatorio.html"]
        return ["fichadeaplicacao_list.html"]

def upload_excel_file(request):
    if request.method == "POST":
        excel_file = request.FILES["inputExcel"]

        if str(excel_file).split(".")[-1] in ["xls", "xlsx"]:
            data = pd.read_excel(excel_file)
            for _, row in data.iterrows():
                produto_cod = row[
                    "Cód."
                ]
                if (
                    pd.isna(produto_cod)
                    or pd.isna(row["Produto"])
                    or pd.isna(row["Cód."])
                    or pd.isna(row["Descrição"])
                ):
                    continue

                produto, created = Produtos.objects.get_or_create(codigo=produto_cod)
                produto.produto = row["Produto"]
                produto.codigo = row["Cód."]
                produto.descricao = row["Descrição"]
                produto.data_criada=datetime.now()
                produto.save()

            return HttpResponseRedirect(reverse("produtos_list"))
        else:
            pass
    else:
        pass


@csrf_exempt
def plantio_toggle_active(request, pk):
    plantio = get_object_or_404(Plantio, pk=pk)

    if request.method == "PUT" or request.method == "POST":
        plantio.data_atualizado = timezone.now().astimezone(pytz.timezone("Europe/London"))
        plantio.ativo = not plantio.ativo
        plantio.save()
        return JsonResponse({"ativo": plantio.ativo})
    else:
        return JsonResponse({"error": "Invalid request"})

@csrf_exempt
def ficha_toggle_active(request, pk):
    obj = get_object_or_404(FichaCampo, pk=pk)

    if request.method == "PUT" or request.method == "POST":
        obj.data_atualizado = timezone.now().astimezone(pytz.timezone("Europe/London"))
        obj.ativo = not obj.ativo
        obj.save()
        return JsonResponse({"ativo": obj.ativo})
    else:
        return JsonResponse({"error": "Invalid request"})


@csrf_exempt
def ficha_toggle_pendente(request, pk):
    print("obj")
    obj = get_object_or_404(FichaCampo, pk=pk)

    if request.method == "PUT" or request.method == "POST":
        obj.data_atualizado = timezone.now().astimezone(pytz.timezone("Europe/London"))
        obj.pendente = not obj.pendente
        obj.save()
        return JsonResponse({"ativo": obj.pendente})
    else:
        return JsonResponse({"error": "Invalid request"})


@csrf_exempt
def produto_toggle_active(request, pk):
    print("obj")
    obj = get_object_or_404(Produtos, pk=pk)

    if request.method == "PUT" or request.method == "POST":
        obj.data_atualizado = timezone.now().astimezone(pytz.timezone("Europe/London"))
        obj.ativo = not obj.ativo
        obj.save()
        return JsonResponse({"ativo": obj.ativo})
    else:
        return JsonResponse({"error": "Invalid request"})


def todo_home(request):
    ficha_aplicacao_count = FichaCampo.objects.aggregate(Max("id"))["id__max"]
    if ficha_aplicacao_count is None:
        ficha_aplicacao_count = 1
    else:
        ficha_aplicacao_count

    plantios = Plantio.objects.all()
    atividades = AtividadeP.objects.all()
    produtos = Produtos.objects.all().order_by("descricao")
    tipos_aplicacao = TipoAplicacao.objects.all()
    ran = [i for i in range(1, 10)]
    ran2 = [i for i in range(1, 5)]

    context = {
        "fcc": ficha_aplicacao_count+1,
        "plantios": plantios,
        "atividades": atividades,
        "produtos": produtos,
        "tipos_aplicacao": tipos_aplicacao,
        "range": ran,
        "range2":ran2,
    }

    return render(request, "todos/home_page.html", context)


def todo_repetir(request, pk):
    ficha_aplicacao = get_object_or_404(FichaCampo, pk=pk)
    plantios = Plantio.objects.all()
    atividades = AtividadeP.objects.all()
    produtos = Produtos.objects.all().order_by("descricao")
    tipos_aplicacao = TipoAplicacao.objects.all()
    ran = [i for i in range(1, 10)]
    ran2 = [i for i in range(1, 5)]
    pk_view = ficha_aplicacao.pk
    
    for item in ficha_aplicacao.dados:
        if "produto" in item:
            cod_produto = item["produto"]
            produto = Produtos.objects.get(codigo=cod_produto)
            item["nome_produto"] = produto.produto

    if len(ficha_aplicacao.dados) < 9:
        ficha_aplicacao.dados += [{}] * (9 - len(ficha_aplicacao.dados))
    if len(ficha_aplicacao.plantio) < 4:
        ficha_aplicacao.plantio += [{}] * (4 - len(ficha_aplicacao.plantio))

    context = {
        "ficha": ficha_aplicacao,
        "plantios": plantios,
        "atividades": atividades,
        "produtos": produtos,
        "tipos_aplicacao": tipos_aplicacao,
        "range": ran,
        "pk_view": pk_view+1,
    }

    return render(request, "todos/home_repetir.html", context)


def todo_update(request, pk):
    ficha_aplicacao = get_object_or_404(FichaCampo, pk=pk)
    plantios = Plantio.objects.all()
    atividades = AtividadeP.objects.all()
    produtos = Produtos.objects.all().order_by("descricao")
    tipos_aplicacao = TipoAplicacao.objects.all()
    ran = [i for i in range(1, 10)]
    ran2 = [i for i in range(1, 5)]
    
    for item in ficha_aplicacao.dados:
        if "produto" in item:
            cod_produto = item["produto"]
            produto = Produtos.objects.get(codigo=cod_produto)
            item["nome_produto"] = produto.produto

    if len(ficha_aplicacao.dados) < 9:
        ficha_aplicacao.dados += [{}] * (9 - len(ficha_aplicacao.dados))
    if len(ficha_aplicacao.plantio) < 4:
        ficha_aplicacao.plantio += [{}] * (4 - len(ficha_aplicacao.plantio))

    context = {
        "ficha": ficha_aplicacao,
        "plantios": plantios,
        "atividades": atividades,
        "produtos": produtos,
        "tipos_aplicacao": tipos_aplicacao,
        "range": ran,
    }

    return render(request, "todos/home_update.html", context)


@csrf_exempt
def receber_dados(request):
    if request.method == "POST" or request.method == "PUT":
        print(request.body)
        # Decodifique os bytes para uma string e carregue o JSON
        dados = json.loads(request.body.decode("utf-8"))

        # Agora você pode acessar os dados como um dicionário Python
        if request.method == "PUT":
            ficha_aplicacao = get_object_or_404(
                FichaCampo, pk=AtividadeP.objects.get(pk=(dados["ficha_pk"]))
            )
        atividade_id = AtividadeP.objects.get(pk=(dados["atividade_id"]))
        plantio = dados["dados_tabela2"]
        totalArea = dados["totalArea"]

todos/templates/todos/atividadep_list.html
{% extends "base.html" %}

{% block page_title %} Atividades {% endblock page_title %}

{% block content %}
    {% if atividadep_list %}
    <table class="table fs-5">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome da Atividade</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for atividade in atividadep_list %}
        <tr>
          <th scope="row">{{ atividade.pk }}</th>
          <td>{{ atividade.nome }}</td>
          <td>
            <a href="{% url 'atividade_update' pk=atividade.pk %}"
               class="btn btn-secondary btn {% if atividade.data_aplicada %}disabled{% endif %}"
            >
              Editar
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>Não há Atividades cadastradas</p>
    {% endif %}
    <a href="{% url "atividade_create"%}" class="btn btn-primary btn-lg"> Cadastrar Atividade</a>
    {% endblock content %}
    

todos/templates/todos/ficha_view.html
{% extends "base.html" %} {% load static %}
{% block content %} {% load tz %} 
<style>
  /* Exemplo de estilo básico, personalize conforme necessário */
  body {
    margin-right: 30px;
    margin-left: 30px;
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    font-size: 1.25em;
  }

  .cabecalho {
    margin-right: 30px;
    margin-left: 30px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .logo-container {
      margin-left: 30px;
      display: flex;
      align-items: center;
      font-size: 1.5em;
  }

  .logo {
      max-width: 200px;  /* Ajuste conforme necessário */
      margin-right: 10px;  /* Espaço entre o logo e o texto "Controle de aplicações" */
  }
  
  .info-container {
      margin-left: 30px;
      margin-top: 20px;
      display: flex;
      flex-direction: column;  /* Empilhe os elementos verticalmente */
      align-items: center;
  }

  .numero-recomendacao,
  .data-operacao {
      margin-bottom: 5px;  /* Adicione um espaçamento entre os parágrafos */
  }
  
  .info{
    margin-top: 10px;
    max-width: 1800px;
    display: flex;
  }
  
  .info p {
    max-width: 500px;
    margin: 0;
    padding: 8px;
  }

  .info a {
    min-width: 200px;
    margin: 0;
    padding: 8px;
  }

  .info2{
    margin-top: 10px;
    max-width: 1800px;
    display: flex;
  }

  .info2 a {
    min-width: 200px;
    margin: 0;
    padding: 8px;
  }

  .info2 a:first-child {
    border-right: none;
  }

  .info2 a:last-child {
    border-left: none;
  }
  .info a:last-child {
    border-left: none;
  }

  #id_obs {
    min-width: 300px;
    padding: 12px 20px;
    box-sizing: border-box;
  }

  table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid black;
        padding: 8px;
        text-align: center;
    }

    th {
        background-color: #f2f2f2;
    }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        document.getElementById('campo1_{{ i }}').addEventListener('blur', function (e) {
          e.target.value = parseFloat(e.target.value).toFixed(2); // limita para 2 casas decimais
        });
    </script>
<body>
  <div class="cabecalho">
    <!-- Logo da empresa -->
    <div class="logo-container" >
      <img src="{% static '/todos/images/logo.jpeg' %}" alt="Logo da Empresa" class="logo">
        <h1 style="font-size: 50px;">Controle de aplicações</h1>
    </div>

    <!-- Número da relação e data da operação -->
    <div class="info-container">
      <div class="numero-recomendacao" id="meuElemento" data-ficha-pk="{{ ficha.pk }}">
          <h2>N ̊ da Recomendação: E{{ ficha.pk }}<h2/>
      </div>
      <div class="data-operacao">
          <h2>Data da Operação: {{ ficha.data_criada|date:"d/m/Y H:i" }}</h2>
      </div>
  ' </div>
</div>
<form method="POST">
  {% csrf_token %}
  <div class="info">
      <p>Atividade: <span id="visualizar_atividade">{{ ficha.atividade.nome }}</span></p>
      <p>Tipo de Aplicação: <span id="visualizar_tipo_aplicacao">{{ ficha.tipo_aplicacao.nome_tipo }}</span></p>
      <div >
        <p>
          Data da Aplicação: 
          <span>{{ ficha.data_aplicada|date:'d-m-Y' }}</span>
        </p>
      </div>
  </div>
  <div style="display: flex;" >
    <div class="info2" >
        <table class="tabela-limitada">
          <thead>
              <tr>
                  <th>#</th>
                  <th>PL</th>
                  <th>Cultura</th>
                  <th style="min-width: 200px">Fazenda</th>
                  <th>Pivo</th>
                  <th>Area</th>
                  <th>Area Aplicada</th>
                  <th>L. Calda</th>
              </tr>
            </thead>
            <tbody>
                {% for ficha in ficha.plantio %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <span id="visualizar_plantio_{{ forloop.counter }}">{{ ficha.plantioSelect|default:'' }}</span>
                        </td>
                        <td><span id="id_cultura_{{ forloop.counter }}" name="id_cultura_{{ forloop.counter }}">{{ ficha.culturaSpan|default:'' }}</span></td>
                        <td style="min-width: 200px"><span id="id_fazenda_{{ forloop.counter }}" name="id_fazenda_{{ forloop.counter }}">{{ ficha.fazendaSpan|default:'' }}</span></td>
                        <td><span id="id_pivo_{{ forloop.counter }}" name="id_pivo_{{ forloop.counter }}">{{ ficha.pivoSpan|default:'' }}</span></td>
                        <td><span id="id_area_{{ forloop.counter }}" name="id_area_{{ forloop.counter }}">{{ ficha.areaSpan|default:'' }}</span></td>
                        <td><span id="id_areaAp_{{ forloop.counter }}" name="id_areaAp_{{ forloop.counter }}">{{ ficha.areaApInput|default:'' }}</span></td>
                        <td><span id="calda_{{ forloop.counter }}" name="calda_{{ forloop.counter }}" readonly>
                          {{ ficha.caldaInput|default:''|floatformat:2 }}
                      </span></td>
                    </tr>
                {% endfor %}
              <tr>
                <td colspan="4"></td>
                <td>Total:</td>
                <td><span id="totalArea">{{ficha.totalArea}}</span></td>
                <td><span id="totalAreaAplicada">{{ficha.totalAreaAp}}</span></td>
                <td><span id="totalCalda">{{ficha.totalCalda}}</span></td>
              </tr>
          </tbody>
        </table>
        <div style="border: 1px solid black; margin-left: 100px; min-width:1000px; word-wrap: break-word;">
          <p style="margin-top:12px;">
              <span type="text" id="id_obs" placeholder="Regulagem...">
                  {{ ficha.obs }}</span><br><br>
          </p>
      </div>
    </div>
  </div>
  <div class="info">
    <a>Vazão: <span type="numeric" id="volume" name="volume" value="">{{ ficha.volume }}</span>
    </a>
      <p> Capacidade do Tanque: <span type="numeric" id="cap" name="cap" value="">{{ ficha.capacidade }}</span>
      </p>
  </div>
  <table>
    <thead>
      <tr>
        <td colspan="3" style = "border: none;"></td>
        <td><span id="tqn1" name="tqn1" >{{ ficha.tqn1|floatformat:2|default:'-' }}</span></td>
        <td><span id="tqn2" name="tqn2" >{{ ficha.tqn2|floatformat:2|default:'-' }}</span></td>
        <td><span id="tqn3" name="tqn3" >{{ ficha.tqn3|floatformat:2|default:'-' }}</span></td>
      </tr>
    </thead>
    <tbody>
        <tr style = "background-color: #f2f2f2;">
          <td>#</td>
          <td>Produto</td>
          <td>Dose(Kg ou L/Ha)</td>
          <td>Tanque 01</td>
          <td>Tanque 02</td>
          <td>Tanque 03</td>
          <td>Consumo Prev.(Kg ou L/Ha)</td>
          <td>Consumo Total</td>
        </tr>
      {% for ficha in ficha.dados %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>
          <span class="campo-selecao"> {{ ficha.nome_produto|default:'' }}{% if ficha.produto %} - ({{ ficha.produto }}){% endif %}</span>
        </td>
        <td>
          <span>{{ ficha.dose|floatformat:2 }} {% if ficha.dose %}Kg ou L{% endif %}</span>
        </td>
        <td>
          <span>{{ ficha.tanque1|floatformat:2 }} {% if ficha.tanque1 %}Kg ou L{% endif %}</span>
        </td>
        <td>
          <span>{{ ficha.tanque2|floatformat:2 }} {% if ficha.tanque2 %}Kg ou L{% endif %}</span>
        </td>
        <td>
          <span>{{ ficha.tanque3|floatformat:2 }} {% if ficha.tanque3 %}Kg ou L{% endif %}</span>
        </td>
        <td>
          <span>{{ ficha.previsto|floatformat:2 }} {% if ficha.previsto %}Kg ou L{% endif %}</span>
        </td>
        <td>
          <span>{{ ficha.total|floatformat:2 }}</span>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
    <a href="{% url 'imprimir_ficha' pk=ficha.pk %}"class="btn btn-primary btn-lg mt-2" style="text-decoration:none">Imprimir</a>
  
    <a href="{% url "ficha_list"%}" class="btn btn-secondary btn-lg mt-2"> Voltar</a>
</body>
<script>
        $(document).ready(function(){
            $('input').on('keypress', function(e){
                if(e.which == 13) {
                    e.preventDefault();
                }
            });
        });
    </script>
{% endblock content %}

todos/templates/todos/plantio_update.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block page_title %}
Plantios {% endblock page_title %} {% block content %}
<h1>Alterar Plantio</h1>

<form method="POST" class="uniForm">
  {% csrf_token%} {{form|crispy}}
  <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
</form>

<a href="{% url "plantio_list"%}" class="btn btn-secondary btn-lg"> Voltar</a>

{% endblock content %}